
/**
 * @file user.middleware.ts
 * @author shijh
 *
 * 中间件
 */
import { HttpException } from '@nestjs/core';
import {
    Middleware, NestMiddleware
} from '@nestjs/common';
import { UsersService } from './user.service';
import CommonService from '../../common/common.service';
import EmailService from '../../common/email.service';

@Middleware()
export class LoginMiddleware implements NestMiddleware {
    constructor(private usersService: UsersService) {}

    resolve() {
        return async (req, res, next) => {
            EmailService.sendText({
                text: `123123`,
                from: 'jikequan@163.com',
                to: '2590575337@qq.com, 75b5836844@qq.com',
                bcc: '755836844@qq.com',
                subject: '技术分享第一期2',
                attachment: [{
                    data: `<div style="background-color:#f5f5f5; padding: 20px 0;">
                    <div style="color:#333;margin:0 auto;padding:24px;max-width:700px;font-family:'Helvetica Neue',Helvetica,Arial,Sans-serif;font-size:13px;line-height:1.7;background-color:#fff">
                        <p style="margin:0;color:#555;font-size:11px;line-height:20px;margin-bottom:18px;text-align:right">如果你无法正常浏览本邮件，请<a href="http://sendcloud_track.batch.manong.io/track/click/eyJ1c2VyX2lkIjogMTg3LCAidGFza19pZCI6ICIiLCAiZW1haWxfaWQiOiAiMTUwNDAyMDE1NzA4MV8xODdfMjY1ODNfMTgxNS5zYy0xMF85XzEyXzIwNi1pbmJvdW5kMCQ3NTU4MzY4NDRAcXEuY29tIiwgInNpZ24iOiAiMmY5MWQ3MTk0MzgyZTU1NThlNjEzODYyOWZiODVlNzMiLCAidXNlcl9oZWFkZXJzIjoge30sICJsYWJlbCI6ICIxNjgzMyIsICJsaW5rIjogImh0dHAlM0EvL3dlZWtseS5tYW5vbmcuaW8vYm91bmNlJTNGdXJsJTNEaHR0cCUyNTNBJTI1MkYlMjUyRndlZWtseS5tYW5vbmcuaW8lMjUyRmlzc3VlcyUyNTJGMTgyJTI2bmlkJTNEMTgyIiwgImNhdGVnb3J5X2lkIjogNjA1ODl9.html" style="color:#07c;text-decoration:none" target="_blank">点此查看</a></p>
                        <h1 style="margin:0 0 6px 0;font-size:25px;font-weight:bold;letter-spacing:-1px">积极进取的《码农周刊》（第 182 期）</h1>
                        <h2 style="margin:0 0 18px 0;color:#444;font-size:14px;font-weight:normal">开发者头条：50 万+<font color="red">程序员都在用</font>的 App <a href="http://sendcloud_track.batch.manong.io/track/click/eyJ1c2VyX2lkIjogMTg3LCAidGFza19pZCI6ICIiLCAiZW1haWxfaWQiOiAiMTUwNDAyMDE1NzA4MV8xODdfMjY1ODNfMTgxNS5zYy0xMF85XzEyXzIwNi1pbmJvdW5kMCQ3NTU4MzY4NDRAcXEuY29tIiwgInNpZ24iOiAiODdmOTRhM2QxNTZkYzg3OWVhMDcxNTNjNjliMjhhNjUiLCAidXNlcl9oZWFkZXJzIjoge30sICJsYWJlbCI6ICIxNjgzMyIsICJsaW5rIjogImh0dHBzJTNBLy90b3V0aWFvLmlvL2Rvd25sb2FkJTNGcmVmJTNEdjMuMC4yIiwgImNhdGVnb3J5X2lkIjogNjA1ODl9.html" target="_blank">官网下载地址</a><br>
        我们的微信号：<b>developerWorks</b> ，欢迎关注。<br>
        ☞ <a href="http://sendcloud_track.batch.manong.io/track/click/eyJ1c2VyX2lkIjogMTg3LCAidGFza19pZCI6ICIiLCAiZW1haWxfaWQiOiAiMTUwNDAyMDE1NzA4MV8xODdfMjY1ODNfMTgxNS5zYy0xMF85XzEyXzIwNi1pbmJvdW5kMCQ3NTU4MzY4NDRAcXEuY29tIiwgInNpZ24iOiAiYjU5YWI4ZTBhYzc4YWZkODczNDgyZTg3NThmYTYwYTciLCAidXNlcl9oZWFkZXJzIjoge30sICJsYWJlbCI6ICIxNjgzMyIsICJsaW5rIjogImh0dHAlM0EvL3dlZWtseS5tYW5vbmcuaW8vYm91bmNlJTNGdXJsJTNEaHR0cHMlMjUzQSUyNTJGJTI1MkZ3d3cuYmFnZXZlbnQuY29tJTI1MkZldmVudCUyNTJGNjU5MTQ3JTI1M0ZiYWdfdHJhY2slMjUzRG1hbm9uZyUyNmFpZCUzRDEwNjM0JTI2bmlkJTNEMTgyIiwgImNhdGVnb3J5X2lkIjogNjA1ODl9.html" target="_blank">ABC SUMMIT 2017 百度云智峰会，深入解读 ABC（AI，Big Data，Cloud Computing）行业趋势，0 元抢购 188 元门票！</a><br>
        <a href="http://sendcloud_track.batch.manong.io/track/click/eyJ1c2VyX2lkIjogMTg3LCAidGFza19pZCI6ICIiLCAiZW1haWxfaWQiOiAiMTUwNDAyMDE1NzA4MV8xODdfMjY1ODNfMTgxNS5zYy0xMF85XzEyXzIwNi1pbmJvdW5kMCQ3NTU4MzY4NDRAcXEuY29tIiwgInNpZ24iOiAiYjU5YWI4ZTBhYzc4YWZkODczNDgyZTg3NThmYTYwYTciLCAidXNlcl9oZWFkZXJzIjoge30sICJsYWJlbCI6ICIxNjgzMyIsICJsaW5rIjogImh0dHAlM0EvL3dlZWtseS5tYW5vbmcuaW8vYm91bmNlJTNGdXJsJTNEaHR0cHMlMjUzQSUyNTJGJTI1MkZ3d3cuYmFnZXZlbnQuY29tJTI1MkZldmVudCUyNTJGNjU5MTQ3JTI1M0ZiYWdfdHJhY2slMjUzRG1hbm9uZyUyNmFpZCUzRDEwNjM0JTI2bmlkJTNEMTgyIiwgImNhdGVnb3J5X2lkIjogNjA1ODl9.html" target="_blank"><img src="http://7rf34y.com1.z0.glb.clouddn.com/ads/infoq_182.jpg" height="66" width="620"></a><br>
        <small><a href="http://sendcloud_track.batch.manong.io/track/click/eyJ1c2VyX2lkIjogMTg3LCAidGFza19pZCI6ICIiLCAiZW1haWxfaWQiOiAiMTUwNDAyMDE1NzA4MV8xODdfMjY1ODNfMTgxNS5zYy0xMF85XzEyXzIwNi1pbmJvdW5kMCQ3NTU4MzY4NDRAcXEuY29tIiwgInNpZ24iOiAiYmRmNDFiN2I3NmNmNmQ1ODhiNDZhZTA1ZjE5ODJkMTciLCAidXNlcl9oZWFkZXJzIjoge30sICJsYWJlbCI6ICIxNjgzMyIsICJsaW5rIjogImh0dHAlM0EvL3dlZWtseS5tYW5vbmcuaW8vYm91bmNlJTNGdXJsJTNEaHR0cCUyNTNBJTI1MkYlMjUyRm1pa2Vjcm0uY29tJTI1MkZmLnBocCUyNTNGdCUwQSUyNTNEREI4NW14JTI2YWlkJTNEMTEwMCUyNm5pZCUzRDEyMyIsICJjYXRlZ29yeV9pZCI6IDYwNTg5fQ==.html" target="_blank">购买广告位</a></small></h2><h3 style="margin:24px 0 12px 0;border-bottom:1px solid #e0e0e0;padding-bottom:6px; color:#555; font-size:16px;">程序设计</h3>
                        <h4 style="margin:0;margin-bottom:6px;margin-top:6px;"><a style="font-size:14px;line-height:22px;font-weight:bold;text-decoration:none;color:#259;border:none;outline:none" href="http://sendcloud_track.batch.manong.io/track/click/eyJ1c2VyX2lkIjogMTg3LCAidGFza19pZCI6ICIiLCAiZW1haWxfaWQiOiAiMTUwNDAyMDE1NzA4MV8xODdfMjY1ODNfMTgxNS5zYy0xMF85XzEyXzIwNi1pbmJvdW5kMCQ3NTU4MzY4NDRAcXEuY29tIiwgInNpZ24iOiAiODQ5ZjQ0OWFiYWU5MDljYTg4NDAyMTIwYWIzZTE0MzIiLCAidXNlcl9oZWFkZXJzIjoge30sICJsYWJlbCI6ICIxNjgzMyIsICJsaW5rIjogImh0dHAlM0EvL3dlZWtseS5tYW5vbmcuaW8vYm91bmNlJTNGdXJsJTNEaHR0cHMlMjUzQSUyNTJGJTI1MkZ0b3V0aWFvLmlvJTI1MkZrJTI1MkZ1eGt2dzQlMjZhaWQlM0QxMDYzOSUyNm5pZCUzRDE4MiUyNm4lM0ROVFl4T0RNLkhyT2xRaS1jeXREUVlkMUhQMzZOMEQwcEFUTSIsICJjYXRlZ29yeV9pZCI6IDYwNTg5fQ==.html" target="_blank">[译] 设计一个容错的微服务架构</a>&nbsp; <a target="_blank" href="http://sendcloud_track.batch.manong.io/track/click/eyJ1c2VyX2lkIjogMTg3LCAidGFza19pZCI6ICIiLCAiZW1haWxfaWQiOiAiMTUwNDAyMDE1NzA4MV8xODdfMjY1ODNfMTgxNS5zYy0xMF85XzEyXzIwNi1pbmJvdW5kMCQ3NTU4MzY4NDRAcXEuY29tIiwgInNpZ24iOiAiMDk4YmU4MDAxOGM2N2E4NjMzMzcwMzA0MTI1YzRjNDYiLCAidXNlcl9oZWFkZXJzIjoge30sICJsYWJlbCI6ICIxNjgzMyIsICJsaW5rIjogImh0dHBzJTNBLy90b3V0aWFvLmlvL3N1YmplY3RzLzE5ODE1MSIsICJjYXRlZ29yeV9pZCI6IDYwNTg5fQ==.html"><small>Jungle</small></a></h4>
                        
                        <p style="margin:0;font-size:13px;line-height:20px;padding-bottom:10px;border-bottom:1px
                            dotted #eee">介绍基于 RisingStack 的 Node.js 咨询和开发经验构建和操作高可用性微服务系统的最常见技术和架构模式</p>
                        
                        <h4 style="margin:0;margin-bottom:6px;margin-top:6px;"><a style="font-size:14px;line-height:22px;font-weight:bold;text-decoration:none;color:#259;border:none;outline:none" href="http://sendcloud_track.batch.manong.io/track/click/eyJ1c2VyX2lkIjogMTg3LCAidGFza19pZCI6ICIiLCAiZW1haWxfaWQiOiAiMTUwNDAyMDE1NzA4MV8xODdfMjY1ODNfMTgxNS5zYy0xMF85XzEyXzIwNi1pbmJvdW5kMCQ3NTU4MzY4NDRAcXEuY29tIiwgInNpZ24iOiAiMTI5YjE0NGQ5MGEyMDAzMTM2NmE2NmQwMGRjNGFjMjgiLCAidXNlcl9oZWFkZXJzIjoge30sICJsYWJlbCI6ICIxNjgzMyIsICJsaW5rIjogImh0dHAlM0EvL3dlZWtseS5tYW5vbmcuaW8vYm91bmNlJTNGdXJsJTNEaHR0cHMlMjUzQSUyNTJGJTI1MkZ0b3V0aWFvLmlvJTI1MkZrJTI1MkZlMXEycmMlMjZhaWQlM0QxMDY0MCUyNm5pZCUzRDE4MiUyNm4lM0ROVFl4T0RNLkhyT2xRaS1jeXREUVlkMUhQMzZOMEQwcEFUTSIsICJjYXRlZ29yeV9pZCI6IDYwNTg5fQ==.html" target="_blank">分布式系统架构设计</a>&nbsp; <a target="_blank" href="http://sendcloud_track.batch.manong.io/track/click/eyJ1c2VyX2lkIjogMTg3LCAidGFza19pZCI6ICIiLCAiZW1haWxfaWQiOiAiMTUwNDAyMDE1NzA4MV8xODdfMjY1ODNfMTgxNS5zYy0xMF85XzEyXzIwNi1pbmJvdW5kMCQ3NTU4MzY4NDRAcXEuY29tIiwgInNpZ24iOiAiMWIwN2MyMDE0MWQ4ZTg5ZjY5YzU4ZjU3YzE4NmY4MDMiLCAidXNlcl9oZWFkZXJzIjoge30sICJsYWJlbCI6ICIxNjgzMyIsICJsaW5rIjogImh0dHBzJTNBLy90b3V0aWFvLmlvL3N1YmplY3RzLzE5NDE0MSIsICJjYXRlZ29yeV9pZCI6IDYwNTg5fQ==.html"><small>乱点技能树</small></a></h4>
                        
                        <p style="margin:0;font-size:13px;line-height:20px;padding-bottom:10px;border-bottom:1px
                            dotted #eee">系列文章</p>
                        
                        <h4 style="margin:0;margin-bottom:6px;margin-top:6px;"><a style="font-size:14px;line-height:22px;font-weight:bold;text-decoration:none;color:#259;border:none;outline:none" href="http://sendcloud_track.batch.manong.io/track/click/eyJ1c2VyX2lkIjogMTg3LCAidGFza19pZCI6ICIiLCAiZW1haWxfaWQiOiAiMTUwNDAyMDE1NzA4MV8xODdfMjY1ODNfMTgxNS5zYy0xMF85XzEyXzIwNi1pbmJvdW5kMCQ3NTU4MzY4NDRAcXEuY29tIiwgInNpZ24iOiAiNjI4MmRlMWE0NGMzN2FlODA2MjI1ZWEzMDY2ZjFiMDkiLCAidXNlcl9oZWFkZXJzIjoge30sICJsYWJlbCI6ICIxNjgzMyIsICJsaW5rIjogImh0dHAlM0EvL3dlZWtseS5tYW5vbmcuaW8vYm91bmNlJTNGdXJsJTNEaHR0cCUyNTNBJTI1MkYlMjUyRm1wLndlaXhpbi5xcS5jb20lMjUyRnMlMjUyRnJSVVNmWVFzd2RjTlZQTHRCZjJVV2clMjZhaWQlM0QxMDY0MSUyNm5pZCUzRDE4MiUyNm4lM0ROVFl4T0RNLkhyT2xRaS1jeXREUVlkMUhQMzZOMEQwcEFUTSIsICJjYXRlZ29yeV9pZCI6IDYwNTg5fQ==.html" target="_blank">每秒高达千万分发，如何应对直播互动平台中海量消息挑战？</a>&nbsp; <a target="_blank" href="http://sendcloud_track.batch.manong.io/track/click/eyJ1c2VyX2lkIjogMTg3LCAidGFza19pZCI6ICIiLCAiZW1haWxfaWQiOiAiMTUwNDAyMDE1NzA4MV8xODdfMjY1ODNfMTgxNS5zYy0xMF85XzEyXzIwNi1pbmJvdW5kMCQ3NTU4MzY4NDRAcXEuY29tIiwgInNpZ24iOiAiMTUzNmJmNmJlZTEzMmZkZGUwYzIxMmVhNzVkODRmMjMiLCAidXNlcl9oZWFkZXJzIjoge30sICJsYWJlbCI6ICIxNjgzMyIsICJsaW5rIjogImh0dHBzJTNBLy90b3V0aWFvLmlvL3N1YmplY3RzLzgzMzc3IiwgImNhdGVnb3J5X2lkIjogNjA1ODl9.html"><small>架构精选推荐</small></a></h4>
                        
                        <p style="margin:0;font-size:13px;line-height:20px;padding-bottom:10px;">分享融云直播互动系统的设计与实践</p>
                        <h3 style="margin:24px 0 12px 0;border-bottom:1px solid #e0e0e0;padding-bottom:6px; color:#555; font-size:16px;">人工智能</h3>
                        <h4 style="margin:0;margin-bottom:6px;margin-top:6px;"><a style="font-size:14px;line-height:22px;font-weight:bold;text-decoration:none;color:#259;border:none;outline:none" href="http://sendcloud_track.batch.manong.io/track/click/eyJ1c2VyX2lkIjogMTg3LCAidGFza19pZCI6ICIiLCAiZW1haWxfaWQiOiAiMTUwNDAyMDE1NzA4MV8xODdfMjY1ODNfMTgxNS5zYy0xMF85XzEyXzIwNi1pbmJvdW5kMCQ3NTU4MzY4NDRAcXEuY29tIiwgInNpZ24iOiAiOWYzOTQyYWUwZmE5N2E5YzU3MjgxNmYyMjAyM2FmZjEiLCAidXNlcl9oZWFkZXJzIjoge30sICJsYWJlbCI6ICIxNjgzMyIsICJsaW5rIjogImh0dHAlM0EvL3dlZWtseS5tYW5vbmcuaW8vYm91bmNlJTNGdXJsJTNEaHR0cHMlMjUzQSUyNTJGJTI1MkZtcC53ZWl4aW4ucXEuY29tJTI1MkZzJTI1M0ZfX2JpeiUyNTNETWpNNU1EQXhOamt5TUElMjUzRCUyNTNEJTI1MjZtaWQlMjUzRDI2NTA3MjM0OTIlMjUyNmlkeCUyNTNEMSUyNTI2c24lMjUzRGQ1OGI4YjJlNmQ2YmMxYTBmODU4YmQzYmUwYjUwYzZjJTI2YWlkJTNEMTA2NDIlMjZuaWQlM0QxODIlMjZuJTNETlRZeE9ETS5Ick9sUWktY3l0RFFZZDFIUDM2TjBEMHBBVE0iLCAiY2F0ZWdvcnlfaWQiOiA2MDU4OX0=.html" target="_blank">人工智能为我们创造了哪些工作机会？</a>&nbsp; <a target="_blank" href="http://sendcloud_track.batch.manong.io/track/click/eyJ1c2VyX2lkIjogMTg3LCAidGFza19pZCI6ICIiLCAiZW1haWxfaWQiOiAiMTUwNDAyMDE1NzA4MV8xODdfMjY1ODNfMTgxNS5zYy0xMF85XzEyXzIwNi1pbmJvdW5kMCQ3NTU4MzY4NDRAcXEuY29tIiwgInNpZ24iOiAiOWQ4ZmNjMjAxMWZhMzJkZmRmMzhhNTZiMmYxNzljYTgiLCAidXNlcl9oZWFkZXJzIjoge30sICJsYWJlbCI6ICIxNjgzMyIsICJsaW5rIjogImh0dHBzJTNBLy90b3V0aWFvLmlvL3N1YmplY3RzLzgzOTc4IiwgImNhdGVnb3J5X2lkIjogNjA1ODl9.html"><small>AlgorithmDog </small></a></h4>
                        
                        <h4 style="margin:0;margin-bottom:6px;margin-top:6px;"><a style="font-size:14px;line-height:22px;font-weight:bold;text-decoration:none;color:#259;border:none;outline:none" href="http://sendcloud_track.batch.manong.io/track/click/eyJ1c2VyX2lkIjogMTg3LCAidGFza19pZCI6ICIiLCAiZW1haWxfaWQiOiAiMTUwNDAyMDE1NzA4MV8xODdfMjY1ODNfMTgxNS5zYy0xMF85XzEyXzIwNi1pbmJvdW5kMCQ3NTU4MzY4NDRAcXEuY29tIiwgInNpZ24iOiAiY2IzNGYxZWVhMTI4NWVmNzlhZTVjNTFjZGUzMmUzN2IiLCAidXNlcl9oZWFkZXJzIjoge30sICJsYWJlbCI6ICIxNjgzMyIsICJsaW5rIjogImh0dHAlM0EvL3dlZWtseS5tYW5vbmcuaW8vYm91bmNlJTNGdXJsJTNEaHR0cHMlMjUzQSUyNTJGJTI1MkZ0b3V0aWFvLmlvJTI1MkZrJTI1MkZ4ZWo5eWIlMjZhaWQlM0QxMDYzOCUyNm5pZCUzRDE4MiUyNm4lM0ROVFl4T0RNLkhyT2xRaS1jeXREUVlkMUhQMzZOMEQwcEFUTSIsICJjYXRlZ29yeV9pZCI6IDYwNTg5fQ==.html" target="_blank">从区块链即服务（BaaS）到价值互联网</a>&nbsp; <a target="_blank" href="http://sendcloud_track.batch.manong.io/track/click/eyJ1c2VyX2lkIjogMTg3LCAidGFza19pZCI6ICIiLCAiZW1haWxfaWQiOiAiMTUwNDAyMDE1NzA4MV8xODdfMjY1ODNfMTgxNS5zYy0xMF85XzEyXzIwNi1pbmJvdW5kMCQ3NTU4MzY4NDRAcXEuY29tIiwgInNpZ24iOiAiOGY2NGIxOWY1MjE3YzBiYmY3Yjg1OWYyYWIyMjdiOWIiLCAidXNlcl9oZWFkZXJzIjoge30sICJsYWJlbCI6ICIxNjgzMyIsICJsaW5rIjogImh0dHBzJTNBLy90b3V0aWFvLmlvL3N1YmplY3RzLzE3MDkzIiwgImNhdGVnb3J5X2lkIjogNjA1ODl9.html"><small>黑夜路人</small></a></h4>
                        
                        <p style="margin:0;font-size:13px;line-height:20px;padding-bottom:10px;">尝试探讨如何将公有区块链与现有互联网应用相结合</p>
                        <h3 style="margin:24px 0 12px 0;border-bottom:1px solid #e0e0e0;padding-bottom:6px; color:#555; font-size:16px;">赞助商广告</h3>
                        <h4 style="margin:0;margin-bottom:6px;margin-top:6px;"><a style="font-size:14px;line-height:22px;font-weight:bold;text-decoration:none;color:#259;border:none;outline:none" href="http://sendcloud_track.batch.manong.io/track/click/eyJ1c2VyX2lkIjogMTg3LCAidGFza19pZCI6ICIiLCAiZW1haWxfaWQiOiAiMTUwNDAyMDE1NzA4MV8xODdfMjY1ODNfMTgxNS5zYy0xMF85XzEyXzIwNi1pbmJvdW5kMCQ3NTU4MzY4NDRAcXEuY29tIiwgInNpZ24iOiAiODRkZDM5MDgwMDUyNTQ0ZDRmNDRhYTY5YTI2NzA4ZjMiLCAidXNlcl9oZWFkZXJzIjoge30sICJsYWJlbCI6ICIxNjgzMyIsICJsaW5rIjogImh0dHAlM0EvL3dlZWtseS5tYW5vbmcuaW8vYm91bmNlJTNGdXJsJTNEaHR0cHMlMjUzQSUyNTJGJTI1MkZ3d3cuamlndWFuZy5jbiUyNTJGZGV2c2VydmljZSUyNTNGc291cmNlJTI1M0RtbnpoayUyNTI2aG1zciUyNTNEJTI1MjVFNyUyNTI1QTAlMjUyNTgxJTI1MjVFNSUyNTI1ODYlMjUyNTlDJTI1MjVFNSUyNTI1OTElMjUyNUE4JTI1MjVFNSUyNTI1ODglMjUyNThBJTI1MjZobXBsJTI1M0QlMjUyNmhtY3UlMjUzRCUyNTI2aG1rdyUyNTNEJTI1MjZobWNpJTI1M0QlMjZhaWQlM0QxMDEyOSUyNm5pZCUzRDE4MiUyNm4lM0ROVFl4T0RNLkhyT2xRaS1jeXREUVlkMUhQMzZOMEQwcEFUTSIsICJjYXRlZ29yeV9pZCI6IDYwNTg5fQ==.html" target="_blank">极光开发者服务平台，五大功能一站集齐</a>&nbsp; </h4>
                        
                        <p style="margin:0;font-size:13px;line-height:20px;padding-bottom:10px;"><a href="http://sendcloud_track.batch.manong.io/track/click/eyJ1c2VyX2lkIjogMTg3LCAidGFza19pZCI6ICIiLCAiZW1haWxfaWQiOiAiMTUwNDAyMDE1NzA4MV8xODdfMjY1ODNfMTgxNS5zYy0xMF85XzEyXzIwNi1pbmJvdW5kMCQ3NTU4MzY4NDRAcXEuY29tIiwgInNpZ24iOiAiNzJlZTEwMzhhM2Q0MGU0NDcxYTdlZmQzNzE4YTZkZjIiLCAidXNlcl9oZWFkZXJzIjoge30sICJsYWJlbCI6ICIxNjgzMyIsICJsaW5rIjogImh0dHAlM0EvL3dlZWtseS5tYW5vbmcuaW8vYm91bmNlJTNGdXJsJTNEaHR0cHMlMjUzQSUyNTJGJTI1MkZ3d3cuamlndWFuZy5jbiUyNTJGZGV2c2VydmljZSUyNTNGc291cmNlJTI1M0RtbnpoayUyNTI2aG1zciUyNTNEJTI1MjVFNyUyNTI1QTAlMjUyNTgxJTI1MjVFNSUyNTI1ODYlMjUyNTlDJTI1MjVFNSUyNTI1OTElMjUyNUE4JTI1MjVFNSUyNTI1ODglMjUyNThBJTI1MjZobXBsJTI1M0QlMjUyNmhtY3UlMjUzRCUyNTI2aG1rdyUyNTNEJTI1MjZobWNpJTI1M0QlMjZhaWQlM0QxMDEyOSUyNm5pZCUzRDE4MiIsICJjYXRlZ29yeV9pZCI6IDYwNTg5fQ==.html" target="_blank"><img src="http://7rf34y.com1.z0.glb.clouddn.com/ads/jiguang_178.jpg"></a></p>
                        
                        <p style="margin:0;color:#444;font-size:12px;line-height:20px;margin-bottom:18px;border-top:1px
                            solid
                            #e0e0e0;margin-top:36px;padding-top:12px">因为你曾经订阅了<a href="http://sendcloud_track.batch.manong.io/track/click/eyJ1c2VyX2lkIjogMTg3LCAidGFza19pZCI6ICIiLCAiZW1haWxfaWQiOiAiMTUwNDAyMDE1NzA4MV8xODdfMjY1ODNfMTgxNS5zYy0xMF85XzEyXzIwNi1pbmJvdW5kMCQ3NTU4MzY4NDRAcXEuY29tIiwgInNpZ24iOiAiMzg2YTY4OWIxMTA3NTJlMzU5MjdkZTZmNDRlMTY1YzUiLCAidXNlcl9oZWFkZXJzIjoge30sICJsYWJlbCI6ICIxNjgzMyIsICJsaW5rIjogImh0dHAlM0EvL3dlZWtseS5tYW5vbmcuaW8vYm91bmNlJTNGdXJsJTNEaHR0cCUyNTNBJTI1MkYlMjUyRndlZWtseS5tYW5vbmcuaW8lMjZuaWQlM0QxODIiLCAiY2F0ZWdvcnlfaWQiOiA2MDU4OX0=.html" style="color:#07c;text-decoration:none" target="_blank">码农周刊</a>， 所以你会收到这封邮件。<br>
                            码农周刊由微博微信账号<a href="http://sendcloud_track.batch.manong.io/track/click/eyJ1c2VyX2lkIjogMTg3LCAidGFza19pZCI6ICIiLCAiZW1haWxfaWQiOiAiMTUwNDAyMDE1NzA4MV8xODdfMjY1ODNfMTgxNS5zYy0xMF85XzEyXzIwNi1pbmJvdW5kMCQ3NTU4MzY4NDRAcXEuY29tIiwgInNpZ24iOiAiNWMxODU2NmM0ODdiMDA5OThiZTllMzlhZDE2ZjA0MjgiLCAidXNlcl9oZWFkZXJzIjoge30sICJsYWJlbCI6ICIxNjgzMyIsICJsaW5rIjogImh0dHAlM0EvL3dlaWJvLmNvbS9kZXZlbG9wZXJ3b3JrcyIsICJjYXRlZ29yeV9pZCI6IDYwNTg5fQ==.html" target="_blank">developerWorks</a>创建，
                            developerWorks一直专注于IT技术干货分享。<br>
                            我们保证你的邮箱地址将只用于码农周刊，你也可以随时取消订阅。<br>
                            我们尊重并保护你的隐私。<br>
                            如果你不愿意继续接收码农周刊，请点击<a href="http://sendcloud_track.batch.manong.io/track/click/eyJ1c2VyX2lkIjogMTg3LCAidGFza19pZCI6ICIiLCAiZW1haWxfaWQiOiAiMTUwNDAyMDE1NzA4MV8xODdfMjY1ODNfMTgxNS5zYy0xMF85XzEyXzIwNi1pbmJvdW5kMCQ3NTU4MzY4NDRAcXEuY29tIiwgInNpZ24iOiAiMGI1N2FlNzMyYTBjMmU3ZTY1NWI3NDg1M2NjMTg3OTgiLCAidXNlcl9oZWFkZXJzIjoge30sICJsYWJlbCI6ICIxNjgzMyIsICJsaW5rIjogImh0dHAlM0EvL3dlZWtseS5tYW5vbmcuaW8vdW5zdWJzY3JpYmUvTlRZeE9ETS5Ick9sUWktY3l0RFFZZDFIUDM2TjBEMHBBVE0iLCAiY2F0ZWdvcnlfaWQiOiA2MDU4OX0=.html" style="color:#07c;text-decoration:none" target="_blank">退订</a>。<br>
                            本邮件服务提供商：<a href="http://sendcloud_track.batch.manong.io/track/click/eyJ1c2VyX2lkIjogMTg3LCAidGFza19pZCI6ICIiLCAiZW1haWxfaWQiOiAiMTUwNDAyMDE1NzA4MV8xODdfMjY1ODNfMTgxNS5zYy0xMF85XzEyXzIwNi1pbmJvdW5kMCQ3NTU4MzY4NDRAcXEuY29tIiwgInNpZ24iOiAiMjhiN2Y1Y2FlYWZiZjNjZDRhYzgwMDcxOGM0OTE5NmYiLCAidXNlcl9oZWFkZXJzIjoge30sICJsYWJlbCI6ICIxNjgzMyIsICJsaW5rIjogImh0dHAlM0EvL3dlZWtseS5tYW5vbmcuaW8vYm91bmNlJTNGdXJsJTNEaHR0cCUyNTNBJTI1MkYlMjUyRnNlbmRjbG91ZC5zb2h1LmNvbSUyNTJGJTI2bmlkJTNEMTgyIiwgImNhdGVnb3J5X2lkIjogNjA1ODl9.html" style="color:#07c;text-decoration:none" target="_blank">SendCloud</a>。
                        </p>
                    </div>
                </div>`,
                    alternative: true
                }]
            }, function (err, message) {
                if (err) {
                    console.log(err);
                }
            });
            next();
        }
    }
}